import type { Metadata } from "next";
import "../globals.css";
import { SideBar } from "@/components/page/sidebar";
import { EngFont } from "@/utils/font";

export const metadata: Metadata = {
  title: "Task Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${EngFont.className} antialiased`}>
        {/* Flex container for layout */}
        <div className="flex h-screen">
          {/* Sidebar */}
          <aside className="w-64">
            <SideBar />
          </aside>

          {/* Main Content */}
          <main className="flex-1 bg-gray-100 p-6 overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
